---
kind: pipeline
name: default

steps:
  - name: weblinks-codeception-tests
    image: joomlaprojects/docker-images:systemtests
    commands:
      - pwd
      - composer install
      - chmod a+x .drone/build.sh
      - ./.drone/build.sh
      - apache2ctl start
      - service mysql start
      - cd /tests/www
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - vendor/bin/robo run:tests

  - name: artifacts-codeception-tests
    image: cschlosser/drone-ftps
    depends_on: [ weblinks-codeception-tests ]
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      PLUGIN_HOSTNAME: artifacts.joomla.org:21
      PLUGIN_SRC_DIR: /tests/_output
      PLUGIN_DEST_DIR: /
      PLUGIN_SECURE: false
      PLUGIN_EXCLUDE: ^\.git/$
    commands:
      - ls -l /drone/src/tests/_output
      - export PLUGIN_DEST_DIR=$PLUGIN_DEST_DIR/$DRONE_REPO/$DRONE_BRANCH/$DRONE_PULL_REQUEST/system-tests/$DRONE_BUILD_NUMBER
      - echo https://artifacts.joomla.org/drone$PLUGIN_DEST_DIR
      - /bin/upload.sh
    when:
      status:
        - failure

volumes:
  - name: weblinks_cache
    host:
      path: /tmp/weblinks_cache

---
kind: signature
hmac: bcc028d5d9601f1f3355862f17dd2434ba86f47634f0737877db534e49c8265b

...
